using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProductCatalog.Api.Domain;

/// <summary>
/// Represents a product in the catalog.
/// This is the core domain entity mapped to the Products table in the database.
/// </summary>
public class Product
{
    /// <summary>
    /// Primary Key — auto-generated by the database (IDENTITY column).
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    /// The display name of the product. Required, max 100 characters.
    /// </summary>
    [Required]
    [MaxLength(100)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// An optional detailed description of the product. Max 500 characters.
    /// </summary>
    [MaxLength(500)]
    public string? Description { get; set; }

    /// <summary>
    /// The price of the product. Stored as decimal with 18 digits and 2 decimal places.
    /// </summary>
    [Required]
    [Column(TypeName = "decimal(18,2)")]
    public decimal Price { get; set; }
}
